# Generated by Django 4.0.4 on 2022-04-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('utrullingsgruppe', models.CharField(choices=[('N', 'Nord'), ('M', 'Midt')], max_length=1)),
                ('annen_info', models.TextField(verbose_name='Annen Info')),
            ],
            options={
                'verbose_name': 'Lokasjon',
                'verbose_name_plural': 'Lokasjoner',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sambandsnr', models.CharField(default='', max_length=255)),
                ('from_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='demo.location')),
                ('to_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='demo.location')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch')], max_length=255)),
                ('network', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('O', 'O')], max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.location')),
            ],
        ),
    ]
