# Generated by Django 4.0.4 on 2022-04-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serialnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterField(
            model_name='location',
            name='utrullingsgruppe',
            field=models.CharField(choices=[('Nord', 'Nord'), ('Midt', 'Midt')], max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.serialnumber'),
        ),
    ]
