# Generated by Django 4.0.4 on 2022-04-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_device_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='circuit_info',
            field=models.CharField(max_length=255, null=True, verbose_name='Samband'),
        ),
        migrations.AlterField(
            model_name='location',
            name='delivery_place',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Kristiansund', 'Kristiansund')], max_length=255, null=True, verbose_name='Leveringssted'),
        ),
    ]
