# Generated by Django 4.0.4 on 2022-04-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_location_circuit_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='network',
        ),
        migrations.AddField(
            model_name='equipment',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Antall'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='function',
            field=models.CharField(choices=[('Kjerneruter P1', 'Kjerneruter P1'), ('Kjerneruter P2A', 'Kjerneruter P2A'), ('Kjerneruter P2B', 'Kjerneruter P2B'), ('Kjerneruter O', 'Kjerneruter O')], max_length=255, null=True, verbose_name='Funksjon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_type',
            field=models.CharField(choices=[('Knutepunkt', 'Knutepunkt'), ('Knutepunkt standard lokasjon', 'Knutepunkt standard lokasjon'), ('Alle', 'Alle')], max_length=255, null=True, verbose_name='Lokasjonstype'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(choices=[('N540', 'N540')], max_length=255, null=True, verbose_name='Modell'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rack_location',
            field=models.CharField(max_length=255, null=True, verbose_name='Plasseres i skap'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.CharField(max_length=255, null=True, verbose_name='Plasseres i rom'),
        ),
    ]
