# Generated by Django 4.0.4 on 2022-04-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_serialnumber_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.equipment'),
        ),
    ]
