# Generated by Django 4.0.4 on 2022-04-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remove_serialnumber_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='from_router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_router', to='demo.equipment'),
        ),
        migrations.AddField(
            model_name='link',
            name='to_router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_router', to='demo.equipment'),
        ),
    ]
