# Generated by Django 4.0.4 on 2022-04-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_link_from_router_link_to_router'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='from_router',
        ),
        migrations.RemoveField(
            model_name='link',
            name='to_router',
        ),
    ]
